# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(db2f98b7-8dac-40d2-a470-4ed4c696698e)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "Test"'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
